apiVersion: v1
kind: Service
metadata:
  name: iam-service
spec:
  type: NodePort
  selector:
    app: iam
  ports:
    - name: http
      port: 80
      targetPort: iam-port
      protocol: TCP
      nodePort: 30000
